Avoid FD and memory leaks
QubesOS/qubes-core-vchan-xen pull request #23
Opened 2022-08-01 17:41 UTC by DemiMarie

See individual commit messages for details.

2022-08-03 12:45 UTC, marmarek requested changes

2022-08-03 12:45 UTC, marmarek commented on vchan/init.c
> +        return ctrl; /* Everything good */
I'd prefer conditional handling an error, and final successful `return` be outside of `if`. It means one more goto label, but IMO is easier to read.

2022-08-03 12:45 UTC, marmarek commented on vchan/io.c
> +            switch (poll(fds, 1, 10)) {
```suggestion
            switch (poll(fds, 1, 10000)) {
```

2022-08-03 12:45 UTC, marmarek commented on vchan/io.c
> +                { .fd = vchan_fd, .events = POLLIN | POLLOUT | POLLPRI | POLLRDHUP, .revents = 0 },
`PULLRDHUP` is not applicable here. `PULLPRI` looks irrelevant for this FD too. `PULLOUT` is actively wrong here.
So, please keep only `PULLIN`.

2022-08-03 16:03 UTC, marmarek requested changes

2022-08-03 16:03 UTC, marmarek commented on vchan/init.c
> +        goto err_xc_open;
trailing space

2022-08-03 18:29 UTC, DemiMarie commented
PipelineRetryFailed

2022-08-29 23:43 UTC, marmarek approved these changes

2022-08-29 23:43 UTC, merged